/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clusters with member counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClusterResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cluster by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cluster ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClusterResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete an empty cluster */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cluster ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description cluster still has member elements */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Rename a cluster's display name/description
         * @description Renaming never touches lookup_key, so the rule engine keeps re-finding this cluster on future matches.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cluster ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description New display name/description */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ClusterRenameRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ClusterResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/discovery/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List discovery jobs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.DiscoveryJobResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Start an async SNMP discovery scan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description IP pool / CIDR / range plus SNMP settings */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.DiscoveryJobRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.DiscoveryJobResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a discovery job's status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.DiscoveryJobResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Best-effort cancel a running discovery job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/jobs/{jobId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a discovery job's per-IP results */
        get: {
            parameters: {
                query?: {
                    /** @description Max rows to return (default 100, max 1000) */
                    limit?: number;
                    /** @description Rows to skip */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Job ID */
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.DiscoveryJobResultResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List network elements */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by cluster ID */
                    cluster_id?: string;
                    /** @description Filter by assignment status (unassigned|assigned) */
                    assignment_status?: string;
                    /** @description Free-text search */
                    q?: string;
                    /** @description Max rows to return (default 100, max 1000) */
                    limit?: number;
                    /** @description Rows to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ElementResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/redistribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run the rule engine for a set of elements (or all, if none given) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Optional element_ids to scope to */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.BulkRedistributeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a network element by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ElementResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Soft-delete a network element */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an element's assignment history timeline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.AssignmentHistoryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elements/{id}/redistribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run the rule engine for one element */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Element ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rules ordered by priority */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RuleResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["dto.RuleRequest"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RuleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder rule priorities */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Ordered rule IDs */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.ReorderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run a candidate rule against a sample hostname
         * @description Evaluates a candidate rule (not necessarily persisted) against a sample hostname and reports what would happen, without writing anything: no element, no cluster, no history row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Candidate rule + sample hostname */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["dto.RuleTestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RuleTestResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rule by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rule ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RuleResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Update a rule */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rule ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["dto.RuleRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RuleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete a rule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rule ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dsl.Arg": {
            i?: number;
            m?: {
                [key: string]: string;
            };
            s?: string;
        };
        "dsl.Op": {
            args?: components["schemas"]["dsl.Arg"][];
            name?: string;
        };
        "dto.AssignmentHistoryResponse": {
            cluster_id?: string;
            created_at?: string;
            id?: string;
            matched_pattern?: string;
            raw_captures?: {
                [key: string]: string;
            };
            rendered_cluster_key?: string;
            rule_id?: string;
            transformed_captures?: {
                [key: string]: string;
            };
            trigger_source?: string;
            warnings?: string;
        };
        "dto.BulkRedistributeRequest": {
            element_ids?: string[];
        };
        "dto.ClusterRenameRequest": {
            description?: string;
            display_name?: string;
        };
        "dto.ClusterResponse": {
            description?: string;
            display_name?: string;
            id?: string;
            lookup_key?: string;
            member_count?: number;
        };
        "dto.DiscoveryJobRequest": {
            snmp_community?: string;
            snmp_version?: string;
            targets?: string;
        };
        "dto.DiscoveryJobResponse": {
            completed_at?: string;
            created_at?: string;
            error_message?: string;
            id?: string;
            input_spec?: string;
            snmp_version?: string;
            started_at?: string;
            status?: string;
            total_targets?: number;
        };
        "dto.DiscoveryJobResultResponse": {
            element_id?: string;
            error_message?: string;
            ip_address?: string;
            responded_at?: string;
            status?: string;
            sys_descr?: string;
            sys_name?: string;
            sys_object_id?: string;
        };
        "dto.ElementResponse": {
            assignment_status?: string;
            cluster_id?: string;
            first_seen_at?: string;
            id?: string;
            ip_address?: string;
            last_rule_id?: string;
            last_seen_at?: string;
            sys_name?: string;
        };
        "dto.ReorderRequest": {
            rule_ids?: string[];
        };
        "dto.RuleRequest": {
            capture_transforms?: {
                [key: string]: components["schemas"]["dsl.Op"][];
            };
            cluster_key_template?: string;
            description?: string;
            is_enabled?: boolean;
            name?: string;
            pattern?: string;
            priority?: number;
        };
        "dto.RuleResponse": {
            capture_transforms?: {
                [key: string]: components["schemas"]["dsl.Op"][];
            };
            cluster_key_template?: string;
            description?: string;
            id?: string;
            is_enabled?: boolean;
            name?: string;
            pattern?: string;
            priority?: number;
        };
        "dto.RuleTestRequest": {
            capture_transforms?: {
                [key: string]: components["schemas"]["dsl.Op"][];
            };
            cluster_key_template?: string;
            hostname?: string;
            pattern?: string;
        };
        "dto.RuleTestResponse": {
            matched?: boolean;
            raw_captures?: {
                [key: string]: string;
            };
            rendered_cluster_key?: string;
            transformed_captures?: {
                [key: string]: string;
            };
            warnings?: string[];
            would_create_new_cluster?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Rule definition */
        "dto.RuleRequest": {
            content: {
                "application/json": components["schemas"]["dto.RuleRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
